Vagrant.configure("2") do |config|

   config.vm.define "vm1" do |vm1|
     vm1.vm.box = "sashatestbox"
	 config.ssh.username = "vagrant"   
	 config.ssh.password = "vagrant"
	 vm1.vm.network "private_network", ip: "192.168.22.11"
	 vm1.vm.network "forwarded_port", guest: 80, host: 8080
	
   end
   config.vm.define "vm2" do |vm2|
      vm2.vm.box = "sashatestbox"
	  config.ssh.username = "vagrant"   
	  config.ssh.password = "vagrant"
	  vm2.vm.provider "virtualbox" do |vb|
  vb.memory = "1024"
  vb.cpus = 4
end
